services:
  mc-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MINECRAFT_VERSION: "1.20.4"
    image: muj-minecraft:1.20.4
    container_name: mc-server
    ports:
      - "25565:25565/tcp"
    environment:
      EULA: "TRUE"
      MEMORY: "2G"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    stop_grace_period: 1m
    restart: unless-stopped
