services:
  prezentace:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lssite26-prezentace
    ports:
      - "8080:80"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
